/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: hello.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as hello_pb from './hello_pb'; // proto import: "hello.proto"


export class SimpleClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/Simple/SayHello',
    grpcWeb.MethodType.UNARY,
    hello_pb.HelloRequest,
    hello_pb.HelloReply,
    (request: hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    hello_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<hello_pb.HelloReply>;

  sayHello(
    request: hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: hello_pb.HelloReply) => void): grpcWeb.ClientReadableStream<hello_pb.HelloReply>;

  sayHello(
    request: hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: hello_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Simple/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Simple/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

  methodDescriptorStreamHello = new grpcWeb.MethodDescriptor(
    '/Simple/StreamHello',
    grpcWeb.MethodType.SERVER_STREAMING,
    hello_pb.HelloRequest,
    hello_pb.HelloReply,
    (request: hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    hello_pb.HelloReply.deserializeBinary
  );

  streamHello(
    request: hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<hello_pb.HelloReply> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/Simple/StreamHello',
      request,
      metadata || {},
      this.methodDescriptorStreamHello);
  }

}

