services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"